[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=gnu++20", "-Wall", "-O2", "-march=native", "-Wextra", "-Wold-style-cast", "-Winit-self", "-Wconversion", "-Wfloat-equal", "-Wlogical-op", "-fconstexpr-depth=2147483647", "-fconstexpr-loop-limit=2147483647", "-fconstexpr-ops-limit=2147483647"]
