name: format-and-verify

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format

    - name: Format with clang-format
      working-directory: main
      run: find . -type f \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-format -i

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: main 
        commit_message: "style: format"

  verify:
    needs: format

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0

    - name: Install oj-verify
      run: pip3 install -U online-judge-verify-helper
      
    - name: Clone ac-library
      uses: actions/checkout@v3
      with:
        repository: atcoder/ac-library
        path: ac-library
        sparse-checkout: atcoder

    - name: Run tests
      working-directory: main
      env:
        CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --timeout=6000
